image: docker:stable

variables:
  # When using dind service we need to instruct docker, to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # Note that if you're using Kubernetes executor, the variable should be set to
  # tcp://localhost:2375 because of how Kubernetes executor connects services
  # to the job container
  DOCKER_HOST: tcp://docker:2375/
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
  CI_REGISTRY_PATH: $CI_REGISTRY/$CI_USERNAME/$CI_PROJECT_NAME

services:
  - docker:dind


stages:
  - Build Docker Image
  # - Push Image to Registry

backend:
  stage: Build Docker Image
  before_script:
    - docker login -u $CI_USERNAME -p $CI_ACCESS_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_PATH/$CI_BACKEND_IMG:latest ./nestpoc-api
    - docker push $CI_REGISTRY_PATH/$CI_BACKEND_IMG:latest
