version: '3'

volumes:
  nestpoc_api:
  nestpoc_ui:

services:
  api:
    container_name: nestpoc-api
    env_file: ${API_ENV_FILE}
    build:
      context: ../nestpoc-api
      dockerfile: ./Dockerfile
    command: node /usr/nestpoc/dist/main.js
    volumes:
      - nestpoc_api:/home/node/app/node_modules
      - nestpoc_api:/usr/nestpoc/node_modules
      - ../nestpoc-api:/home/node/app
    ports:
      - ${API_PORT}:3000

  ui:
    container_name: nestpoc-ui
    build:
      context: ../nestpoc-ui
      dockerfile: ./Dockerfile
    volumes:
      - nestpoc_ui:/home/node/app/node_modules
      - ../nestpoc-ui:/home/node/app
    ports:
      - ${UI_PORT}:80
