version: '3'

volumes:
  nestpoc_api:
  nestpoc_ui:

services:
  backend:
    env_file: ../nestpoc-api/production.env
    build:
      context: ../nestpoc-api
      dockerfile: ./Dockerfile
    command: node /usr/nestpoc/dist/main.js
    volumes:
      - nestpoc_api:/home/node/app/node_modules
      - nestpoc_api:/usr/nestpoc/node_modules
      - ../nestpoc-api:/home/node/app
    ports:
      - '3000:3000'
    environment:
      PORT: 3000

  frontend:
    build:
      context: ../nestpoc-ui
      dockerfile: ./Dockerfile
    command: /bin/sh
    volumes:
      - nestpoc_ui:/home/node/app/node_modules
      - ../nestpoc-ui:/home/node/app
    ports:
      - ${UI_PORT}:80
    environment:
      PORT: 80
